# Generated by Django 3.1.4 on 2020-12-28 11:11

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='text',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
